version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: carmago-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carmago-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/carmago-auth
    depends_on:
      - mongo

  frontend:
    image: nginx:alpine
    container_name: carmago-frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  mongo-data:
